import json
from pathlib import Path

from engine.ai_generation import validate_generated_identity
from engine.approval import evaluate_for_approval
from engine.claim_evidence import audit_claim_evidence
from engine.draft_packets import build_draft_packet

ROOT = Path(__file__).resolve().parents[1]
CASE_DIR = ROOT / "agent" / "results" / "v2-quality-smoke-001"


def _load(name: str) -> dict:
    return json.loads((CASE_DIR / name).read_text(encoding="utf-8"))


def test_v2_quality_smoke_article_passes_full_approval_pipeline():
    blueprint = _load("blueprint.json")
    article = _load("article.json")
    packet = build_draft_packet(blueprint)

    # Prove the article's worked example matches the packet generated by V2.
    assert packet["case_bundle"]["draws"][-12:] == [
        "06162", "94806", "25595", "63151", "90428", "76110",
        "08593", "58125", "23592", "41229", "85669", "60816",
    ]
    assert packet["case_bundle"]["omission"]["current_omission"] == {
        0: 6, 1: 8, 2: 3, 3: 5, 4: 12, 5: 4, 6: 0, 7: 12, 8: 7, 9: 1,
    }
    assert packet["case_bundle"]["omission"]["candidates_meeting_threshold"] == [0, 1, 2, 3, 4, 5, 7, 8]

    # Same immutable identity contract used after a real Responses API call.
    validate_generated_identity(packet, article)

    evidence = audit_claim_evidence(packet, article)
    assert evidence.passed, evidence.errors

    result = evaluate_for_approval(packet, article)
    assert result.approved, result.errors
    assert result.status == "approved"
    assert result.quality_score == 100
    assert result.errors == []
    assert result.publish_package is not None
    assert result.publish_package["article_id"] == article["article_id"]
    assert result.publish_package["content"] == article["content"]
